Add lint
jellyfish-dev/jellyfish-react-client pull request #10
Opened 2023-03-29 08:05 UTC by ostatni5

2023-03-30 12:47 UTC, kamil-stasiak requested changes

2023-03-30 12:47 UTC, kamil-stasiak commented on examples/dashboard/src/components/CameraTest.tsx
> +// type IdToStream = Record<string, MediaStream>;
```suggestion
```

2023-03-30 12:47 UTC, kamil-stasiak commented on .eslintignore
> +dist
```suggestion
node_modules
dist

```

2023-03-30 12:47 UTC, kamil-stasiak commented on examples/dashboard/.eslintignore
> +dist
```suggestion
node_modules
dist

```

2023-03-30 12:47 UTC, kamil-stasiak commented on src/externalState/index.ts
> +export { createNoContextMembraneClient } from "./createNoContextMembraneClient";
```suggestion
export { createNoContextMembraneClient } from "./createNoContextMembraneClient";

```

2023-03-30 12:47 UTC, kamil-stasiak commented on src/jellyfish/index.ts
> +export * from './addLogging'
```suggestion
export * from './JellyfishClient'
export * from './addLogging'

```

2023-03-30 12:47 UTC, kamil-stasiak commented on src/stateMappers.tsx
> +  <PeerMetadata, TrackMetadata>(_metadata?: unknown) =>
investigate metadata type

2023-03-30 12:47 UTC, kamil-stasiak commented on tsconfig.json
> +    "module": "ESNext",
investigate Motule resolution

2023-04-03 08:29 UTC, ostatni5 commented on tsconfig.json
> +    "module": "ESNext",
[Browsers support `ES` modules. ](https://www.tsmean.com/articles/learn-typescript/typescript-module-compiler-option/)

2023-04-04 14:30 UTC, merged